apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsify-backend
  namespace: devopsify
  labels:
    app: devopsify-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devopsify-backend
  template:
    metadata:
      labels:
        app: devopsify-backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/senudajk/devopsify-backend:latest
        ports:
        - containerPort: 5001
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "5001"
        - name: MONGODB_URI
          value: "mongodb://admin:password123@devopsify-mongodb:27017/devopsify?authSource=admin"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: devopsify-backend
  namespace: devopsify
spec:
  ports:
  - port: 5001
    targetPort: 5001
  selector:
    app: devopsify-backend
