apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsify-mongodb
  namespace: devopsify
  labels:
    app: devopsify-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devopsify-mongodb
  template:
    metadata:
      labels:
        app: devopsify-mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:6.0
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "admin"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "password123"
        - name: MONGO_INITDB_DATABASE
          value: "devopsify"
        volumeMounts:
        - name: mongodb-storage
          mountPath: /data/db
      volumes:
      - name: mongodb-storage
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: devopsify-mongodb
  namespace: devopsify
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: devopsify-mongodb
