apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: devopsify
type: Opaque
stringData:
  username: admin
  password: "SecurePassword123!"  # Change this in production
  
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: devopsify
type: Opaque
stringData:
  secret: "ChangeThisJWTSecretInProduction123!"  # Change this in production
