# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: devopsify-backend-service
  namespace: devopsify
  labels:
    app: devopsify-backend
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 5001
    targetPort: 5001
    protocol: TCP
    name: http
  selector:
    app: devopsify-backend

---
# Backend Service Alias (for nginx compatibility)
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: devopsify
  labels:
    app: devopsify-backend
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 5001
    targetPort: 5001
    protocol: TCP
    name: http
  selector:
    app: devopsify-backend