# Frontend Service (LoadBalancer for public access)
apiVersion: v1
kind: Service
metadata:
  name: devopsify-frontend-service
  namespace: devopsify
  labels:
    app: devopsify-frontend
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: devopsify-frontend