# MongoDB Database Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsify-mongodb
  namespace: devopsify
  labels:
    app: devopsify-mongodb
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devopsify-mongodb
  template:
    metadata:
      labels:
        app: devopsify-mongodb
        tier: database
    spec:
      containers:
      - name: mongodb
        image: mongo:7.0
        ports:
        - containerPort: 27017
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 300m
            memory: 512Mi
        volumeMounts:
        - name: mongodb-storage
          mountPath: /data/db
      volumes:
      - name: mongodb-storage
        emptyDir: {}