# name: CI

# on:
#   push:
#     branches:
#       - main
#       - dev
#       - feature/*
#   pull_request:
#     branches:
#       - main
#       - dev

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: '14'

#       - name: Install frontend dependencies
#         working-directory: ./src/frontend
#         run: npm install

#       - name: Build frontend
#         working-directory: ./src/frontend
#         run: npm run build

#       - name: Install backend dependencies
#         working-directory: ./src/backend
#         run: npm install

#       - name: Run backend tests
#         working-directory: ./src/backend
#         run: npm test

#       - name: Run security scan
#         run: npx trivy image --exit-code 1 --severity HIGH,CRITICAL your-docker-image:latest

#       - name: Build Docker image
#         run: docker build -t your-docker-image:latest .

#       - name: Push Docker image
#         run: |
#           echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
#           docker push your-docker-image:latest