name: Pull Request Checks

on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    name: Validate Pull Request

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check PR title format
      run: |
        PR_TITLE="${{ github.event.pull_request.title }}"
        echo "PR Title: $PR_TITLE"
        
        if [[ "$PR_TITLE" =~ ^(feat|fix|docs|style|refactor|test|chore):.+ ]]; then
          echo "✅ PR title follows convention"
        else
          echo "❌ PR title should follow format: 'type: description'"
          exit 1
        fi